with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/sanchey92/sso/internal/usecase/user:
    interfaces:
      UserRepository:
      PasswordHasher:
      CacheStore:
      EmailSender:
      TokenValidator:
      TokenRevoker:

  github.com/sanchey92/sso/internal/usecase/auth:
    interfaces:
      UserGetter:
      PasswordVerifier:
      TokenIssuer:
      MFAChallengeIssuer:
      MFATokenValidator:
      TOTPVerifier:
      RecoveryVerifier:

  github.com/sanchey92/sso/internal/usecase/oauth:
    interfaces:
      ClientGetter:
      ClientAuthenticator:
      AuthCodeStore:
      TokenIssuer:
      TokenRefresher:

  github.com/sanchey92/sso/internal/usecase/token:
    interfaces:
      TokenGenerator:
      RefreshTokenRepository:

  github.com/sanchey92/sso/internal/usecase/client:
    interfaces:
      OAuthRepository:

  github.com/sanchey92/sso/internal/usecase/federation:
    interfaces:
      IdentityProvider:
      UserLinker:
      TokenIssuer:
      StateStore:

  github.com/sanchey92/sso/internal/usecase/mfa:
    interfaces:
      UserGetter:
      Updater:
      Encryptor:
      RecoveryCodeRepo:
      RecoveryReader:

  github.com/sanchey92/sso/internal/usecase/magiclink:
    interfaces:
      UserGetter:
      CacheStore:
      LinkSender:
      TokenIssuer:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/auth:
    interfaces:
      AuthService:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/user:
    interfaces:
      UserService:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/userinfo:
    interfaces:
      InfoProvider:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/token:
    interfaces:
      TokenService:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/client:
    interfaces:
      OAuthService:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/oauth:
    interfaces:
      OAuthorizer:
      Exchanger:
      Refresher:
      Revoker:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/federation:
    interfaces:
      Initiator:
      CallbackHandler:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/mfa:
    interfaces:
      TOTPService:
      TokenValidator:
      Completer:

  github.com/sanchey92/sso/internal/adapter/driving/rest/handler/magiclink:
    interfaces:
      LinkRequester:
      LinkVerifier:

  github.com/sanchey92/sso/internal/adapter/driving/grpc/handler:
    interfaces:
      TokenIntrospector:
      UserGetter:
      IntrospectionCache: