with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/sanchey92/sso/internal/usecase/user:
    interfaces:
      UserRepository:
      PasswordHasher:
      CacheStore:
      EmailSender:
  github.com/sanchey92/sso/internal/usecase/auth:
    interfaces:
      UserGetter:
      PasswordVerifier:
      TokenIssuer:
  github.com/sanchey92/sso/internal/usecase/token:
    interfaces:
      TokenGenerator:
      RefreshTokenRepository:
  github.com/sanchey92/sso/internal/adapter/driving/rest:
    interfaces:
      UserService:
      AuthService:
      TokenService:
