version: 3

dotenv: [ '.env' ]

vars:
  GO_VERSION: '1.26'
  GOLANGCI_LINT_VERSION: 'v2.10.1'
  GOOSE_VERSION: 'v3.24.1'
  MOCKERY_VERSION: 'v2.53.3'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GOOSE: '{{.BIN_DIR}}/goose'
  MOCKERY: '{{.BIN_DIR}}/mockery'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'

tasks:
  build:
    desc: build the application
    cmds:
      - go build -o {{.BIN_DIR}}/$APP_NAME ./cmd/sso/

  run:
    desc: run the application
    deps:
      - build
    cmds:
      - '{{.BIN_DIR}}/$APP_NAME'

  test:
    desc: run unit tests
    cmds:
      - go clean -testcache
      - go test ./... -v -race -count=1

  test:cover:
    desc: run unit tests with coverage and open report in browser
    vars:
      COVER_DIR: '{{.ROOT_DIR}}/coverage'
    cmds:
      - go clean -testcache
      - mkdir -p {{.COVER_DIR}}
      - go test ./... -race -count=1 -coverprofile={{.COVER_DIR}}/coverage.out -covermode=atomic
      - go tool cover -func={{.COVER_DIR}}/coverage.out
      - go tool cover -html={{.COVER_DIR}}/coverage.out -o {{.COVER_DIR}}/coverage.html
      - open {{.COVER_DIR}}/coverage.html

  test:integration:
    desc: run integration tests
    cmds:
      - go clean -testcache
      - go test ./... -v -race -count=1 -tags=integration

  format:
    desc: "format gofumpt + gci"
    silent: true
    deps: [ install-formatters ]
    cmds:
      - find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +
      - find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/sanchey92/sso/)" {} +

  install:tools:
    desc: install all tools
    cmds:
      - task: install:golangci-lint
      - task: install:goose
      - task: install:mockery
      - task: install-formatters

  install-formatters:
    desc: "install formatters"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
      - GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  install:golangci-lint:
    desc: install golangci-lint
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - test -f {{.GOLANGCI_LINT}}

  install:goose:
    desc: install goose
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}
    status:
      - test -f {{.GOOSE}}

  install:mockery:
    desc: install mockery
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
    status:
      - test -x {{.MOCKERY}}

  lint:
    desc: run golangci-lint
    deps:
      - install:golangci-lint
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml'

  migrate:up:
    desc: migrations up
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" up'

  migrate:down:
    desc: migrations rollback
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" down'

  migrate:status:
    desc: migrations status
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" status'

  migrate:create:
    desc: create new migrations (usage - task migrate:create -- name_of_migration)
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR create {{.CLI_ARGS}} sql'

  mockery:gen:
    desc: generate mocks
    deps:
      - install:mockery
    cmds:
      - |
        echo 'mocks gen...'
        {{.MOCKERY}}

