version: 3

dotenv: ['.env']

vars:
  GO_VERSION: '1.26'
  GOLANGCI_LINT_VERSION: 'v2.10.1'
  GOOSE_VERSION: 'v3.24.1'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GOOSE: '{{.BIN_DIR}}/goose'

tasks:
  build:
    desc: build the application
    cmds:
      - go build -o {{.BIN_DIR}}/$APP_NAME ./cmd/sso/

  run:
    desc: run the application
    deps:
      - build
    cmds:
      - '{{.BIN_DIR}}/$APP_NAME'

  test:
    desc: run unit tests
    cmds:
      - go test ./... -v -race -count=1

  test:integration:
    desc: run integration tests
    cmds:
      - go test ./... -v -race -count=1 -tags=integration

  install:tools:
    desc: install all tools
    cmds:
      - task: install:golangci-lint
      - task: install:goose

  install:golangci-lint:
    desc: install golangci-lint
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - test -f {{.GOLANGCI_LINT}}

  install:goose:
    desc: install goose
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - GOBIN={{.BIN_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}
    status:
      - test -f {{.GOOSE}}

  lint:
    desc: run golangci-lint
    deps:
      - install:golangci-lint
    cmds:
      - '{{.GOLANGCI_LINT}} run ./... --config=.golangci.yml'

  migrate:up:
    desc: migrations up
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" up'

  migrate:down:
    desc: migrations rollback
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" down'

  migrate:status:
    desc: migrations status
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR postgres "$POSTGRES_DSN" status'

  migrate:create:
    desc: create new migrations (usage - task migrate:create -- name_of_migration)
    deps:
      - install:goose
    cmds:
      - '{{.GOOSE}} -dir $MIGRATIONS_DIR create {{.CLI_ARGS}} sql'
