global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: sso
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['app:9090']
        labels:
          service: sso
          environment: docker
